### ISSUE TITLE
Sync this with the original repo and point the original repo to here

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/HtmlRenderer#60]
Aka pull all commits from https://github.com/ArthurHub/HTML-Renderer and submit a pull request to that repo changing the Help Wanted section with a pointer to here

**Comment by Happypig375** [comment]
https://github.com/prepare/HTML-Renderer

This branch is 2652 commits ahead, **265 commits behind ArthurHub:master**.

**Comment by prepare** [comment]
I still don't have a plan for pull/submit/sync the https://github.com/prepare/HTML-Renderer
with the original https://github.com/ArthurHub/HTML-Renderer 
because I changed it in many areas and 
it dose not fit with the original project requirements.

eg. I removed WPF, Pdf supports (I have a plan for support it later)

I'm sure that the original community will not happy with this

:)

and origina

**Comment by prepare** [comment]
and since   https://github.com/prepare/HTML-Renderer is 2652 commits ahead.
The project's _Network graph_ may disturb the user of the original repo, 
so I switch the my old fork to this  https://github.com/LayoutFarm/HtmlRenderer/
